// Copyright (C) 2014 Diego Herranz

#include <pic18fregs.h>
#include <delay.h>
#include <stdint.h>

// FUSES START
// Minimum modifications needed. Rest of fuses left as default.

//The code generated by SDCC does probably not work when XINST (extended instruction set) is enabled
#pragma config XINST=OFF

// Oscillator Selection bits (Internal oscillator, port function on RA6, EC used by USB (INTIO))
#pragma config FOSC = INTOSCIO_EC

// Watchdog timer OFF
#pragma config WDT = OFF

// Single-Supply ICSP OFF
#pragma config LVP = OFF

// FUSES END

uint8_t number_to_7seg(uint8_t number)
{
	switch (number) {
		case 0:
			return 0x3F;
		case 1:
			return 0x06;
		case 2:
			return 0x5B;
		case 3:
			return 0x4F;
		case 4:
			return 0x66;
		case 5:
			return 0x6D;
		case 6:
			return 0x7D;
		case 7:
			return 0x07;
		case 8:
			return 0x7F;
		case 9:
			return 0x6F;
		default:
			return 0;
	}
}


void main(void)
{
	uint8_t i;

	TRISB = 0; // Pins as output
	LATB = 0; // LEDs off
	
	while (1) {
		for (i = 0; i < 10; i++) {
			LATB = number_to_7seg(i);
			delay1ktcy(250); //1s @ 1MHz	
		}		
	}
}
