// Copyright (C) 2014 Diego Herranz

#include <pic18fregs.h>

//The code generated by SDCC does probably not work when XINST (extended instruction set) is enabled
#pragma config XINST=OFF

void main(void)
{
}
