#include <pic18fregs.h>
#include <delay.h>

//The code generated by SDCC does probably not work when XINST (extended instruction set) is enabled
#pragma config XINST=OFF

// Oscillator Selection bits (Internal oscillator, port function on RA6, EC used by USB (INTIO))
#pragma config FOSC = INTOSCIO_EC

#define LED_LAT LATCbits.LATC0
#define LED_TRIS TRISCbits.TRISC0

void main(void){

	LED_TRIS = 0; // Pin as output
	LED_LAT = 0; // LED off
	
	while(1){
		LED_LAT = !LED_LAT; // Toggle LED
		delay1ktcy(125); //500ms @ 1MHz
	}

}
